import '../styles/globals.css'
import Header from "@/components/Header";
import Footer from "@/components/Footer";



export const metadata = {
  title: 'Movify',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={" px-8"}>
        <Header/>
        {children}
        <Footer/>
      </body>
    </html>
  )
}
